Added `action_mode`
Mubelotix/cli_progress_bar pull request #5
Opened 2022-10-22 15:36 UTC by brainwo

This pull request add an extra option `action_mode`. This option is to specify what format used for displaying the bar.

`Mode::Number` is the default behavior, it prints `{progression}/{max}` (e.g. `1/123`) in the end of the bar.
`Mode::Percentage` prints the progress percentage with two decimals (e.g. `12.34%`) in the end of the bar.
`Mode::Nothing` not printing any additional info.

2022-10-23 08:30 UTC, Mubelotix requested changes
I love it! I think it would be even better if the mode was stored as a field in the ProgressBar struct. I would like to not break existing code, so let's avoid adding new parameters to existing functions and methods. Instead, create new similar functions with a `_with_mode` suffix.

2022-10-23 11:07 UTC, brainwo commented
> I would like to not break existing code, so let's avoid adding new parameters to existing functions and methods.

That's a good idea. Perhaps we can make all the options (`Style`, `Color`, `Mode`) to a single struct then use `..Default::default()` to have a default configured ProgressBar. But that's more suitable to the next breaking release.

2022-10-28 16:39 UTC, Mubelotix commented
I like this better, thanks! Could you add another method and global function to only set the mode and not the action please? I actually wonder if it's relevant to have a method to change both at the same time.

2025-08-25 11:36 UTC, Mubelotix commented
Hello, I'm closing this because it's stale. Thank you for the code, someone might reuse it

2025-08-25 11:36 UTC, closed without merging